# Generated by Django 4.0.5 on 2022-08-20 09:02

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('entity_name', models.CharField(max_length=100)),
                ('industry_name', models.CharField(choices=[('agency_sales_housing', 'Agency & Sales Housing'), ('art_and_design', 'Art & Design'), ('automation', 'Automation'), ('construction', 'Construction'), ('consulting', 'Consulting'), ('consumer_packaged_goods', 'Consumer Packaged Goods'), ('education', 'Education'), ('engineering', 'Engineering'), ('entertainment', 'Entertainment'), ('financial_services', 'Financial Services'), ('food_services', 'Food Services (Restaurants/Fast Food)'), ('gaming', 'Gaming'), ('government', 'Government'), ('healthcare', 'Health Care'), ('interior_design', 'Interior Design'), ('legal', 'Legal'), ('manufacturing', 'Manufacturing'), ('marketing', 'Marketing'), ('mining_and_logistics', 'Mining and Logistics'), ('non_profit', 'Non-Profit'), ('publishing_and_media', 'Publishing and Web Media'), ('real_estate', 'Real Estate'), ('retail', 'Retail (E-Commerce and Retails)'), ('services', 'Services'), ('technology', 'Technology'), ('telecommunications', 'Telecommunications'), ('travel_hospitality', 'Travel/Hospitality')], max_length=100)),
                ('contact_person', models.CharField(max_length=100)),
                ('contact_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('company_email', models.EmailField(max_length=50, null=True)),
                ('gst_number', models.CharField(blank=True, max_length=20, null=True)),
                ('pan_number', models.CharField(blank=True, max_length=20, null=True)),
                ('pf_number', models.CharField(blank=True, max_length=20, null=True)),
                ('esic_number', models.CharField(blank=True, max_length=20, null=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authentication.client')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(blank=True, null=True)),
                ('work_profile', models.TextField(blank=True, null=True)),
                ('key_info', models.TextField(blank=True, null=True)),
                ('specific_request', models.TextField(blank=True, null=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cprofile.company')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line', models.TextField()),
                ('locality', models.CharField(max_length=50, null=True)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(choices=[('maharashtra', 'Maharashtra '), ('andhra_pradesh', 'Andhra Pradesh'), ('arunachal_pradesh', 'Arunachal Pradesh'), ('assam', 'Assam'), ('bihar', 'Bihar'), ('chhattisgarh', 'Chhattisgarh'), ('goa', 'Goa'), ('delhi', 'Delhi'), ('gujarat', 'Gujarat'), ('haryana', 'Haryana'), ('himachal_pradesh', 'Himachal Pradesh'), ('jammu_and_kashmir', 'Jammu and Kashmir'), ('jharkhand', 'Jharkhand'), ('karnataka', 'Karnataka'), ('kerala', 'Kerala'), ('madhya_pradesh', 'Madhya Pradesh'), ('manipur', 'Manipur'), ('meghalaya', 'Meghalaya'), ('mizoram', 'Mizoram'), ('nagaland', 'Nagaland'), ('odisha', 'Odisha'), ('punjab', 'Punjab'), ('rajasthan', 'Rajasthan'), ('sikkim', 'Sikkim'), ('tamil_nadu', 'Tamil Nadu'), ('telangana', 'Telangana'), ('tripura', 'Tripura'), ('uttar_pradesh', 'Uttar Pradesh'), ('uttarakhand', 'Uttarakhand'), ('west_bengal', 'West Bengal')], max_length=30)),
                ('country', models.CharField(default='India', max_length=30)),
                ('pin_code', models.CharField(max_length=6)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cprofile.company')),
            ],
        ),
        migrations.CreateModel(
            name='BankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=50)),
                ('account_number', models.CharField(max_length=15)),
                ('ifsc_code', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cprofile.company')),
            ],
        ),
    ]
