# Generated by Django 4.0.5 on 2022-08-27 04:07

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companycontext',
            name='about',
            field=froala_editor.fields.FroalaField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companycontext',
            name='key_info',
            field=froala_editor.fields.FroalaField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companycontext',
            name='specific_request',
            field=froala_editor.fields.FroalaField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companycontext',
            name='work_profile',
            field=froala_editor.fields.FroalaField(blank=True, null=True),
        ),
    ]
